module.exports = {
   trailingComma: 'es5',
   tabWidth: 3,
   semi: false,
   singleQuote: true,
   importOrder: [
      '^(react/(.*)$)|^(react$)',
      '^(next/(.*)$)|^(next$)',
      '<THIRD_PARTY_MODULES>',
      '',
      '^types$',
      '^@/env(.*)$',
      '^@/types/(.*)$',
      '^@/config/(.*)$',
      '^@/lib/(.*)$',
      '^@/hooks/(.*)$',
      '^@/components/ui/(.*)$',
      '^@/components/(.*)$',
      '^@/styles/(.*)$',
      '^@/app/(.*)$',
      '',
      '^[./]',
   ],
   importOrderSeparation: false,
   importOrderSortSpecifiers: true,
   importOrderBuiltinModulesToTop: true,
   plugins: [
      require('prettier-plugin-tailwindcss'),
      '@ianvs/prettier-plugin-sort-imports',
   ],
}
